import { z } from 'zod';
import { addExpenseSchema } from '@/lib/validations/expenses';

export type AddExpenseType = z.infer<typeof addExpenseSchema>;

export enum ExpenseCategory {
  // Fully Deductible Business Expenses
  COST_OF_GOODS = 'COST_OF_GOODS',
  RENT_RATES = 'RENT_RATES',
  UTILITIES = 'UTILITIES',
  SALARIES_WAGES = 'SALARIES_WAGES',
  REPAIRS_MAINTENANCE = 'REPAIRS_MAINTENANCE',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  SOFTWARE_SUBSCRIPTIONS = 'SOFTWARE_SUBSCRIPTIONS',
  PROFESSIONAL_FEES = 'PROFESSIONAL_FEES',
  INSURANCE = 'INSURANCE',
  LICENSES_PERMITS = 'LICENSES_PERMITS',
  ADVERTISING = 'ADVERTISING',
  BANK_CHARGES = 'BANK_CHARGES',
  TRAINING = 'TRAINING',

  // Partially Deductible Business Expenses = "// Partially Deductible Business Expenses",
  INTEREST_ON_DEBT = 'INTEREST_ON_DEBT',
  BAD_DEBTS = 'BAD_DEBTS',
  DONATIONS = 'DONATIONS',
  DEPRECIATION = 'DEPRECIATION',
  RESEARCH_DEVELOPMENT = 'RESEARCH_DEVELOPMENT',
  ENTERTAINMENT = 'ENTERTAINMENT',

  // Individual/Employee Expenses = "// Individual/Employee Expenses",
  PERSONAL_EXPENSES = 'PERSONAL_EXPENSES',
  RESIDENTIAL_RENT = 'RESIDENTIAL_RENT',
  TRANSPORTATION = 'TRANSPORTATION',

  // Non-Deductible Expenses = "// Non-Deductible Expenses",
  FINES_PENALTIES = 'FINES_PENALTIES',
  BENEFITS_IN_KIND = 'BENEFITS_IN_KIND',
  NON_APPROVED_PENSION = 'NON_APPROVED_PENSION',
  PERSONAL_LIVING_EXPENSES = 'PERSONAL_LIVING_EXPENSES',

  // Other Expenses = "// Other Expenses",
  OTHER = 'OTHER',
}

// ============================================================================
// EXPENSE CATEGORIES WITH EMBEDDED TAX PROPERTIES
// ============================================================================

export const expensesCategories = [
  // Fully Deductible Business Expenses
  {
    value: ExpenseCategory.COST_OF_GOODS,
    label: 'Cost of Goods Sold',
    subcategories: [
      { value: 'raw_materials', label: 'Raw Materials' },
      { value: 'direct_labor', label: 'Direct Labor' },
      { value: 'manufacturing_costs', label: 'Manufacturing Costs' },
      { value: 'freight_in', label: 'Freight In' },
      { value: 'customs_duties', label: 'Customs Duties' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Direct costs attributable to the production of goods sold',
    note: 'Fully deductible when directly related to production of goods',
  },
  {
    value: ExpenseCategory.RENT_RATES,
    label: 'Rent & Rates',
    subcategories: [
      { value: 'office_rent', label: 'Office Rent' },
      { value: 'warehouse_rent', label: 'Warehouse Rent' },
      { value: 'shop_rent', label: 'Shop Rent' },
      { value: 'property_rates', label: 'Property Rates' },
      { value: 'ground_rent', label: 'Ground Rent' },
      { value: 'residential_rent', label: 'Residential Rent' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner', 'employed'],
    description:
      'Cost of renting business premises and residential accommodation',
    note: 'Business premises fully deductible. Residential rent has specific limits for employed individuals',
  },
  {
    value: ExpenseCategory.UTILITIES,
    label: 'Utilities',
    subcategories: [
      { value: 'electricity', label: 'Electricity' },
      { value: 'water', label: 'Water' },
      { value: 'gas', label: 'Gas' },
      { value: 'internet', label: 'Internet' },
      { value: 'telephone', label: 'Telephone' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Business utility expenses',
    note: 'Fully deductible for business use',
  },
  {
    value: ExpenseCategory.SALARIES_WAGES,
    label: 'Salaries & Wages',
    subcategories: [
      { value: 'salaries', label: 'Salaries' },
      { value: 'wages', label: 'Wages' },
      { value: 'bonuses', label: 'Bonuses' },
      { value: 'commissions', label: 'Commissions' },
      { value: 'overtime', label: 'Overtime Pay' },
      { value: 'paye_tax', label: 'PAYE Tax Withheld' },
      { value: 'pension_contributions', label: 'Pension Contributions' },
      { value: 'nhf_contributions', label: 'NHF Contributions' },
      { value: 'nhis_contributions', label: 'NHIS Contributions' },
      { value: 'itf_contributions', label: 'ITF Contributions' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['business-owner'],
    description:
      'All employee compensation and related statutory contributions',
    note: 'Fully deductible when paid to employees',
  },
  {
    value: ExpenseCategory.REPAIRS_MAINTENANCE,
    label: 'Repairs & Maintenance',
    subcategories: [
      { value: 'building_repairs', label: 'Building Repairs' },
      { value: 'equipment_repairs', label: 'Equipment Repairs' },
      { value: 'vehicle_repairs', label: 'Vehicle Repairs' },
      { value: 'machinery_maintenance', label: 'Machinery Maintenance' },
      { value: 'it_maintenance', label: 'IT Maintenance' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Costs of repairing and maintaining business assets',
    note: 'Fully deductible when maintaining existing assets (not improving)',
  },
  {
    value: ExpenseCategory.OFFICE_SUPPLIES,
    label: 'Office Supplies',
    subcategories: [
      { value: 'stationery', label: 'Stationery' },
      { value: 'printing', label: 'Printing' },
      { value: 'furniture', label: 'Office Furniture' },
      { value: 'equipment', label: 'Office Equipment' },
      { value: 'cleaning_supplies', label: 'Cleaning Supplies' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Supplies and equipment for office operations',
    note: 'Fully deductible when used for business purposes',
  },
  {
    value: ExpenseCategory.SOFTWARE_SUBSCRIPTIONS,
    label: 'Software & Subscriptions',
    subcategories: [
      { value: 'accounting_software', label: 'Accounting Software' },
      { value: 'productivity_software', label: 'Productivity Software' },
      { value: 'industry_software', label: 'Industry-Specific Software' },
      { value: 'cloud_services', label: 'Cloud Services' },
      { value: 'data_subscription', label: 'Data Subscription' },
      { value: 'website_hosting', label: 'Website Hosting' },
    ],
    defaultDeductionPercentage: 25,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Software licenses and subscription services',
    note: 'Qualifies for 25% capital allowance as intangible asset',
  },
  {
    value: ExpenseCategory.PROFESSIONAL_FEES,
    label: 'Professional Fees',
    subcategories: [
      { value: 'legal_fees', label: 'Legal Fees' },
      { value: 'accounting_fees', label: 'Accounting Fees' },
      { value: 'consulting_fees', label: 'Consulting Fees' },
      { value: 'audit_fees', label: 'Audit Fees' },
      { value: 'tax_advisory', label: 'Tax Advisory' },
      { value: 'engineering_fees', label: 'Engineering Fees' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Fees paid to professional service providers',
    note: 'Fully deductible when directly related to business operations',
  },
  {
    value: ExpenseCategory.INSURANCE,
    label: 'Insurance',
    subcategories: [
      { value: 'business_insurance', label: 'Business Insurance' },
      { value: 'liability_insurance', label: 'Liability Insurance' },
      { value: 'property_insurance', label: 'Property Insurance' },
      { value: 'professional_indemnity', label: 'Professional Indemnity' },
      { value: 'key_man_insurance', label: 'Key Man Insurance' },
      {
        value: 'personal_health_insurance',
        label: 'Personal Health Insurance',
      },
      { value: 'personal_life_insurance', label: 'Personal Life Insurance' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner', 'employed'],
    description: 'Business and personal insurance premiums',
    note: 'Business insurance fully deductible. Personal insurance may have specific limits for employed individuals',
  },
  {
    value: ExpenseCategory.LICENSES_PERMITS,
    label: 'Licenses & Permits',
    subcategories: [
      { value: 'business_license', label: 'Business License' },
      { value: 'operating_permit', label: 'Operating Permit' },
      { value: 'industry_certification', label: 'Industry Certification' },
      { value: 'professional_license', label: 'Professional License' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Cost of business licenses and permits',
    note: 'Fully deductible when required for business operations',
  },
  {
    value: ExpenseCategory.ADVERTISING,
    label: 'Advertising & Promotion',
    subcategories: [
      { value: 'online_ads', label: 'Online Advertising' },
      { value: 'print_ads', label: 'Print Advertising' },
      { value: 'tv_radio_ads', label: 'TV/Radio Advertising' },
      { value: 'billboards', label: 'Billboards' },
      { value: 'promotional_materials', label: 'Promotional Materials' },
      { value: 'sponsorships', label: 'Sponsorships' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Marketing and advertising expenses',
    note: 'Fully deductible when directly related to business promotion',
  },
  {
    value: ExpenseCategory.BANK_CHARGES,
    label: 'Bank Charges',
    subcategories: [
      { value: 'account_maintenance', label: 'Account Maintenance' },
      { value: 'transaction_fees', label: 'Transaction Fees' },
      { value: 'overdraft_charges', label: 'Overdraft Charges' },
      { value: 'foreign_exchange', label: 'Foreign Exchange Fees' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Banking and financial service charges (excluding interest)',
    note: 'Fully deductible when for business accounts',
  },
  {
    value: ExpenseCategory.TRAINING,
    label: 'Training & Development',
    subcategories: [
      { value: 'employee_training', label: 'Employee Training' },
      { value: 'professional_development', label: 'Professional Development' },
      { value: 'workshops_seminars', label: 'Workshops & Seminars' },
      { value: 'conferences', label: 'Conferences' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Training and development expenses',
    note: 'Fully deductible when directly related to business operations',
  },

  // Partially Deductible Business Expenses
  {
    value: ExpenseCategory.INTEREST_ON_DEBT,
    label: 'Interest on Debt',
    subcategories: [
      { value: 'bank_loan_interest', label: 'Bank Loan Interest' },
      { value: 'mortgage_interest', label: 'Mortgage Interest' },
      { value: 'bond_interest', label: 'Bond Interest' },
      { value: 'supplier_credit_interest', label: 'Supplier Credit Interest' },
    ],
    defaultDeductionPercentage: 30,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Interest paid on business loans and other debts',
    note: 'Subject to 30% EBITDA limit as per Section 20(a) of the Tax Act',
  },
  {
    value: ExpenseCategory.BAD_DEBTS,
    label: 'Bad Debts',
    subcategories: [
      { value: 'written_off_receivables', label: 'Written Off Receivables' },
      { value: 'doubtful_debts', label: 'Doubtful Debts' },
      { value: 'provision_for_bad_debts', label: 'Provision for Bad Debts' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Uncollectible debts written off',
    note: 'Must prove irrecoverable as per Section 20(h) of the Tax Act',
  },
  {
    value: ExpenseCategory.DONATIONS,
    label: 'Donations',
    subcategories: [
      { value: 'charitable_donations', label: 'Charitable Donations' },
      { value: 'educational_donations', label: 'Educational Donations' },
      { value: 'religious_donations', label: 'Religious Donations' },
      { value: 'government_funds', label: 'Government Funds' },
    ],
    defaultDeductionPercentage: 10,
    workTypes: ['self-employed', 'freelancer', 'business-owner', 'employed'],
    description: 'Donations to approved charitable organizations',
    note: 'Maximum 10% of profit as per Section 164 of the Tax Act',
  },
  {
    value: ExpenseCategory.DEPRECIATION,
    label: 'Depreciation',
    subcategories: [
      { value: 'buildings', label: 'Buildings' },
      { value: 'plant_machinery', label: 'Plant & Machinery' },
      { value: 'vehicles', label: 'Vehicles' },
      { value: 'furniture_fixtures', label: 'Furniture & Fixtures' },
      { value: 'computer_equipment', label: 'Computer Equipment' },
      { value: 'intangible_assets', label: 'Intangible Assets' },
    ],
    defaultDeductionPercentage: 20,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Depreciation on capital assets',
    note: 'Varies by asset type: Buildings 10%, Plant/Equipment 20%, Vehicles/Software 25%',
  },
  {
    value: ExpenseCategory.RESEARCH_DEVELOPMENT,
    label: 'Research & Development',
    subcategories: [
      { value: 'product_research', label: 'Product Research' },
      { value: 'process_development', label: 'Process Development' },
      { value: 'innovation_projects', label: 'Innovation Projects' },
      { value: 'patent_costs', label: 'Patent Costs' },
    ],
    defaultDeductionPercentage: 5,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Research and development expenses',
    note: 'Maximum 5% of turnover + 50% additional deduction as per Section 165 of the Tax Act',
  },
  {
    value: ExpenseCategory.ENTERTAINMENT,
    label: 'Entertainment',
    subcategories: [
      { value: 'client_entertainment', label: 'Client Entertainment' },
      { value: 'staff_entertainment', label: 'Staff Entertainment' },
      { value: 'hospitality', label: 'Hospitality' },
      { value: 'events', label: 'Events' },
    ],
    defaultDeductionPercentage: 50,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Entertainment expenses',
    note: 'Often 50% or less deductible as per Section 21 of the Tax Act',
  },

  // Individual/Employee Expenses
  {
    value: ExpenseCategory.PERSONAL_EXPENSES,
    label: 'Personal Expenses',
    subcategories: [
      { value: 'personal_pension', label: 'Personal Pension Contributions' },
      {
        value: 'personal_health_insurance',
        label: 'Personal Health Insurance',
      },
      { value: 'personal_life_insurance', label: 'Personal Life Insurance' },
      { value: 'personal_education', label: 'Personal Education' },
      { value: 'dependent_care', label: 'Dependent Care' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'employed'],
    description: 'Personal expenses that may be deductible for individuals',
    note: 'Subject to specific limits and conditions under the Tax Act',
  },
  {
    value: ExpenseCategory.RESIDENTIAL_RENT,
    label: 'Residential Rent',
    subcategories: [
      { value: 'house_rent', label: 'House Rent' },
      { value: 'apartment_rent', label: 'Apartment Rent' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['employed'],
    description: 'Residential accommodation for employees',
    note: 'Deductible for employed individuals with specific limits',
  },
  {
    value: ExpenseCategory.TRANSPORTATION,
    label: 'Transportation',
    subcategories: [
      { value: 'vehicle_expenses', label: 'Vehicle Expenses' },
      { value: 'fuel', label: 'Fuel' },
      { value: 'maintenance', label: 'Vehicle Maintenance' },
      { value: 'insurance', label: 'Vehicle Insurance' },
      { value: 'public_transport', label: 'Public Transport' },
      { value: 'travel_allowance', label: 'Travel Allowance' },
      { value: 'airfare', label: 'Airfare' },
      { value: 'hotel_accommodation', label: 'Hotel Accommodation' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner', 'employed'],
    description: 'Business transportation and travel expenses',
    note: 'For employed individuals, only work-related transportation is deductible',
  },

  // Non-Deductible Expenses
  {
    value: ExpenseCategory.FINES_PENALTIES,
    label: 'Fines & Penalties',
    subcategories: [
      { value: 'regulatory_fines', label: 'Regulatory Fines' },
      { value: 'late_payment_penalties', label: 'Late Payment Penalties' },
      { value: 'breach_of_contract', label: 'Breach of Contract Penalties' },
      { value: 'traffic_violations', label: 'Traffic Violations' },
    ],
    defaultDeductionPercentage: 0,
    workTypes: ['self-employed', 'freelancer', 'business-owner', 'employed'],
    description: 'Fines and penalties (non-deductible)',
    note: 'Explicitly non-deductible as per Section 21 of the Tax Act',
  },
  {
    value: ExpenseCategory.BENEFITS_IN_KIND,
    label: 'Benefits in Kind',
    subcategories: [
      { value: 'company_car', label: 'Company Car' },
      { value: 'accommodation', label: 'Accommodation' },
      { value: 'meals', label: 'Meals' },
      { value: 'club_membership', label: 'Club Membership' },
      { value: 'other_perks', label: 'Other Perks' },
    ],
    defaultDeductionPercentage: 0,
    workTypes: ['employed', 'business-owner'],
    description: 'Benefits in kind received by employees',
    note: 'Special rules apply as per Section 14 of the Tax Act',
  },
  {
    value: ExpenseCategory.NON_APPROVED_PENSION,
    label: 'Non-Approved Pension',
    subcategories: [
      { value: 'unapproved_scheme', label: 'Unapproved Pension Scheme' },
      { value: 'over_contributions', label: 'Over Contributions' },
    ],
    defaultDeductionPercentage: 0,
    workTypes: ['self-employed', 'freelancer', 'employed', 'business-owner'],
    description: 'Non-approved pension contributions',
    note: 'Non-deductible as per Section 21 of the Tax Act',
  },
  {
    value: ExpenseCategory.PERSONAL_LIVING_EXPENSES,
    label: 'Personal Living Expenses',
    subcategories: [
      { value: 'groceries', label: 'Groceries' },
      { value: 'clothing', label: 'Clothing' },
      { value: 'personal_care', label: 'Personal Care' },
      { value: 'hobbies', label: 'Hobbies' },
      { value: 'vacations', label: 'Vacations' },
    ],
    defaultDeductionPercentage: 0,
    workTypes: ['self-employed', 'freelancer', 'employed', 'business-owner'],
    description: 'Personal living expenses (non-deductible)',
    note: 'Explicitly non-deductible as per Section 21 of the Tax Act',
  },

  // Other Expenses
  {
    value: ExpenseCategory.OTHER,
    label: 'Other Expenses',
    subcategories: [
      { value: 'miscellaneous', label: 'Miscellaneous' },
      { value: 'unclassified', label: 'Unclassified' },
    ],
    defaultDeductionPercentage: 100,
    workTypes: ['self-employed', 'freelancer', 'business-owner'],
    description: 'Other business expenses not classified elsewhere',
    note: 'Deductibility depends on nature of expense',
  },
];
